### ISSUE TITLE
Timeout problem using Words with "R" at the beginning of a line

### ISSUE THREAD

**Issue by computerlyrik** [computerlyrik/dymoprint#15]
With some String combinations the connection times out. Still unclear what it is causing it, but it is reproducable:

```bash
./dymoprint -s b "Rose Regenbogen" "" "03.05.2017"
Printing label..
Traceback (most recent call last):
  File "./dymoprint", line 576, in <module>
    main(args)
  File "./dymoprint", line 570, in main
    lm.printLabel(labelmatrix)
  File "./dymoprint", line 202, in printLabel
    self.rawPrintLabel(lines, margin=margin)
  File "./dymoprint", line 224, in rawPrintLabel
    response = self.sendCommand()
  File "./dymoprint", line 103, in sendCommand
    responseBin = self.dev.read(8)
IOError: [Errno 110] Connection timed out
```

The device needs at least a power-cycle to run again.

**Comment by computerlyrik** [comment]
@bbinet  you seem to be more in the code than me, recently. Any ideas?

**Comment by bbinet** [comment]
It does work for me, but maybe your dymo is not the same as mine.
You can try to decrease the `maxLines` value:
https://github.com/computerlyrik/dymoprint/blob/f34cc3a1a9672bdc438811fa12e951af6cfc0ef7/dymoprint#L90

**Comment by computerlyrik** [comment]
```
./dymoprint -s b "Dietes iridioides" "14-Tages-Lilie" "03.05.2017"
```

Works like a charm.

**Comment by computerlyrik** [comment]
Tried out `maxLines=400`. Did not work out.

**Comment by bbinet** [comment]
I meant decrease, not increase ;)

**Comment by computerlyrik** [comment]
Ha! Got it (WTF included):
```bash 
./dymoprint -s b " Rose Regenbogen" "" "03.05.2017"
```
It is the **R** at the beginning of the line. Adding a empty space in front works like a charm.

How i got it:
```bash
./dymoprint -s b " Ranunculus asiaticus" "Asiatischer Hahnenfuss (Mix)" "03.05.2017"
```
Same thing.

Yes, it is only **R**. _r_ at the beginning of a line works fine.

**Comment by bbinet** [comment]
That is weird. It is working perfectly with or without `R` for me...

**Comment by bbinet** [comment]
Note that I'm using font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf

**Comment by computerlyrik** [comment]
I will leave this here. Perhaps it is some problem with my `zsh`. Never faced this before.

**Comment by computerlyrik** [comment]
Confirmed working now on my machine.
```
python --version
Python 3.7.2
```
