### ISSUE TITLE
QR code printing broken

### ISSUE THREAD

**Issue by andreas5232** [computerlyrik/dymoprint#27]
Using the recent master branch (8c1014cf9833a80739e123ac985855071e6070a1) breaks the qr code printing for me. Unfortunately I'm not that familiar with Python, so I was unable to figure out a solution myself. I'm currently running an Arch Linux with Python 3.7.2.

Last working commit: 5e912dae59ad5a5a4b8851cdbeaeefbda1ae8aab

> user@machine ~/dymoprint$ ./dymoprint -qr "Test"
> ./dymoprint:402: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
>  conf = SafeConfigParser(FONT_CONFIG)
> Traceback (most recent call last):
> File "./dymoprint", line 590, in <module> 
>   main(args)
>  File "./dymoprint", line 500, in main
>    die("Error: %s" % e_qrcode)
>NameError: name 'e_qrcode' is not defined

**Comment by computerlyrik** [comment]
Should be fixed by now. Please try again.

**Comment by andreas5232** [comment]
QR code printing works again. Thanks for the fix! :)
