### ISSUE TITLE
Device permissions

### ISSUE THREAD

**Issue by 4project-co-il** [computerlyrik/dymoprint#32]
Hi,

Can't manage to solve the device permissions so the script won't need root permissions to print.

I've copied the files:
sudo cp 91-dymo-labelmanager-pnp.rules /etc/udev/rules.d/
sudo cp dymo-labelmanager-pnp.conf /etc/usb_modeswitch.d/    

And added the lines as the script suggested:
ACTION=="add", SUBSYSTEMS=="usb", ATTRS{idVendor}=="0922", ATTRS{idProduct}=="1001", MODE="0660", GROUP="users"
ACTION=="add", SUBSYSTEMS=="usb", ATTRS{idVendor}=="0922", ATTRS{idProduct}=="1002", MODE="0660", GROUP="users"

Unplugged the device, plugged it in again, but the script still need root permissions to print :(

Will appreciate your help with that.

Thanks.

**Comment by computerlyrik** [comment]
Hey @abetis,
thus every System is configured differently we cannot provide common linux support here.

You should be aware what these lines do. E.g. find out if the VendorID and ProductID are correctly set by instrumenting `lsusb`. Or see if your user is in the `users` group.

For a one-time-workaround, if the script says "cannot access /dev/something" try to do a `sudo chown myloginuser /dev/something` and try again. But this vanishes as soon as you re-plug the device.

If any questions about the software itself, don't be afraid to ask.

**Comment by 4project-co-il** [comment]
I understand that you can't provide system support.
Was frustrated since everything looked ok, but still the permissions didn't allow to print.

Moved to another PC where the provided rules did work properly.

By the way, the script suggests to add different lines compared to the rules in github

**Comment by computerlyrik** [comment]
@abetis  Thank you for reporting the documentation inconsistency!
