### ISSUE TITLE
Operation timed out

### ISSUE THREAD

**Issue by 4project-co-il** [computerlyrik/dymoprint#33]
Hi,

Did you encounter "Operation timed out" on the device?
For now disconnecting/connecting the device again doesn't help.
Restarting udev didn't help as well...
Will try to reboot soon.

I get that printout:
Traceback (most recent call last):
  File "/usr/bin/dymoprint", line 323, in <module>
    main()
  File "/usr/bin/dymoprint", line 319, in main
    lm.print_label(labelmatrix, dottab)
  File "/usr/bin/dymoprint", line 241, in print_label
    response = self.send_command()
  File "/usr/bin/dymoprint", line 141, in send_command
    rspBin = self.status.read(8)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 402, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 988, in read
    self.__get_timeout(timeout))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 851, in intr_read
    timeout)
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out

**Comment by computerlyrik** [comment]
Please have a look at the issues https://github.com/computerlyrik/dymoprint/issues/15 and https://github.com/computerlyrik/dymoprint/issues/2 if they apply.

Perhaps you try to use another device or another OS.

Also, please try
- a virtualenv python with py2 and py3 and see if problems persist
- call directly from git checkout - the path `/usr/bin/dymoprint` worries me a little
- add more info about your bug, eg OS, command you tried, output of `lsusb`, output `ls -lah /dev/yourDevice` and whatever think may help.

Currently with the latest versions, i am able to print looooong texts even with QR and Barcode included on even loonger labels. Everything fine.

Anyone else experiencing the same problems like @abetis ?

Perhaps you may find someone in here providing basic linux support, but no promises ;)

**Comment by 4project-co-il** [comment]
Actually I'm printing  very small labels.
I've placed the script in /usr/bin since I need it to be in a common place for all the users, so the PHP script run from apache could access it.

Here are some more details, but I'm not sure it will be enough to debug.
Since the problem is gone now, I think it will be a waste of time to dive into that issue right now.

I had the timeout on my server when tried to play first with the dymoprint. Don't remember what I did, but the issue disappeared there. It could be unplug/plug the device or could be PC restart. I remember that I was trying to fix the permissions problem to print on the device.

Moved to another machine to deploy the script and change the local system to access the device from apache. Had the same problems with permissions. What I do remember, when I set permissions in udev rules file to 0666 (allow other to print as well), I always got the timeout.
My solution was to leave the permission 0660 and add apache's user to plugdev group (that's the group that your default udev rule assign to the device).

Another strange thing is that unplugging/plugging in the device, as well as "systemctr restart udev" doesn't seems to reload the udev rule. Only full PC restart fixed the permissions problem...

**Comment by computerlyrik** [comment]
Not reproducable.

**Comment by 0uro** [comment]
Completely forgot virtualenv, and it works fine in it. So it's not dymoprint the culprit
closing, thanks for your help !

**Comment by maresb** [comment]
@0uro, did you mean to comment on #42 instead?

Good point about venv. I modified the README to recommend installing with pipx so that the venv is taken care of automatically.

**Comment by niekvugteveen** [comment]
Same issue
python3 -m venv ./
dymoprint "test"

Fixed it.
