### ISSUE TITLE
Letter "C" issue - stucks while printing

### ISSUE THREAD

**Issue by 0uro** [computerlyrik/dymoprint#42]
Hello,

Your program works perfectly, when I'm not trying to print something that begins with capital c the print stucks and I get this : 

-> ./dymoprint -s b "CCCCC"
Printing label..
Traceback (most recent call last):
  File "./dymoprint", line 632, in <module>
    main(args)
  File "./dymoprint", line 626, in main
    lm.printLabel(labelmatrix)
  File "./dymoprint", line 215, in printLabel
    self.rawPrintLabel(lines, margin=margin)
  File "./dymoprint", line 237, in rawPrintLabel
    response = self.sendCommand()
  File "./dymoprint", line 116, in sendCommand
    responseBin = self.dev.read(8)
TimeoutError: [Errno 110] Connection timed out

**Comment by maresb** [comment]
Strange, works fine for me.

![image](https://user-images.githubusercontent.com/15216687/144721513-4fbc6d03-c000-404c-b940-889a23dd8d7f.png)

Are you using the latest version? What's the output of `dymoprint --version`?

**Comment by 0uro** [comment]
version 1.2.0

I managed to print the capital C once, right after plugging it in. Next print with capital C ahead brings the problem back.

**Comment by maresb** [comment]
Hmm, I'm also on 1.2.0, and I just printed three times in a row with no problem.

You can print other letters, just not `C`?

**Comment by maresb** [comment]
I wonder if there could be a problem with your battery. See [page 6 of the LabelMaker User Guide](https://download.dymo.com/dymo/user-guides/LabelManager/LMPnP/LMPnP_UserGuide_en-US.pdf#page=8). In case you need to replace it, here's the corresponding [product](https://www.dymo.com/label-makers-printers/labelmanager-label-makers/dymo-lithium-ion-li-ion-battery-for-labelmanager-260p-280p-and-pnp-label-makers/SAP_1758458.html).

In any case, it'd be nice to figure out the status codes, for which I've opened #43.

**Comment by nathancatlow** [comment]
This is definitely a battery problem, I had exactly the same issue, printer would print immediately after turning on, but then would partly print, hang or I/O error or connection timed out... After chasing around with linux, udev, cups, usblp I eventually stumbled on this issue. I rigged a DC power supply to the battery terminals and the printer worked fine. I have ordered a new battery.

**Comment by maresb** [comment]
@nathancatlow do you have the status codes and/or voltage for your dying battery? Based on your readings in #43 with the power supply, it doesn't seem to me like we'd be able to recognize anything until the voltage drops all the way down to 2.5v.

**Comment by maresb** [comment]
I suppose we could try to catch the "Connection timed out" error and suggest the user to check their battery.

**Comment by nathancatlow** [comment]
I'm really sorry, I should have done that. I dismantled the old battery and welded in new cells as I refused to pay £25. It might be measuring something else, internal resistance maybe? I agree that you should probably catch the I/O errors and hint at the battery being the issue. To be honest, I completely forgot there was one in there.

**Comment by maresb** [comment]
No worries, glad you have it running on your own terms, and thanks so much for all the info!

**Comment by maresb** [comment]
Since this seems to be a battery issue, I'm going to close this and instead point to #43 as the main thread for if we can detect and report on battery status.
