### ISSUE TITLE
No .ini file example in the README

### ISSUE THREAD

**Issue by ajlennon** [computerlyrik/dymoprint#45]
I had a little investigate and this type of thing seems to work

`~/.config/dymoprint.ini `

```
[FONTS]
regular=/usr/share/fonts/truetype/freefont/FreeMono.ttf
```

**Comment by maresb** [comment]
Thanks for the report. We provide a sample `dymoprint.ini` in the project root, but maybe it's confusing that it's not linked from the readme. Does [this](https://github.com/computerlyrik/dymoprint/commit/4f95fcada21c21780514164c682003d26c80a308) help?

**Comment by ajlennon** [comment]
Awesome thanks! (Love the tool as well!)
