### ISSUE TITLE
No module named 'fcntl'

### ISSUE THREAD

**Issue by karolzlot** [computerlyrik/dymoprint#49]
After installing:
```
pipx install dymoprint
```
I tried to run it:

```
dymoprint MyText
```

but I got:
```
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by karolzlot** [comment]
Ah, this doesn't support Windows.

**Comment by maresb** [comment]
I hope that we can support Windows soon, but that will require a bit of work and testing.
