### ISSUE TITLE
tostring() has been removed. Please call tobytes() instead.

### ISSUE THREAD

**Issue by dcast78** [computerlyrik/dymoprint#5]
File "./dymoprint", line 440, in <module>
    main()
  File "./dymoprint", line 408, in main
    labelstream = labelrotated.tostring()
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 695, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.

Changed as suggested as worked for me, please check if is correct. (Tested on Debian 8).

**Comment by computerlyrik** [comment]
fixed in https://github.com/computerlyrik/dymoprint/pull/4
