### ISSUE TITLE
right margin broken in 1.4.0

### ISSUE THREAD

**Issue by tedder** [computerlyrik/dymoprint#57]
With 1.4.0 installed there's no right margin. I tried `-a` and `-j` and a few other things, but to repro all I have to do is install 1.3.1. It's a 12mm tape, simply calling it with one line:
```
dymoprint "FOO"
```

The label has no right margin, it simply cuts the tape at the end of the word. Let me know if you want pictures or anything else; I would've thought cf78767add6845e9456c2dd1b91550c95438eef4 was the _fix_ for this, but then I assume you committed c19a65b49372b840d66fc81219315d7c4d51237d for a reason. But installing from current head (ff26705) does not have a proper margin either:
```
$ pip3 install git+https://github.com/computerlyrik/dymoprint.git@master
...
$ dymoprint --version
dymoprint 1.4.0.post1.dev2+gff26705
```

**Comment by maresb** [comment]
Thanks for the detailed report @tedder. I can reproduce this issue.

@MooVx, could you please take a look when you get the chance?

**Comment by maresb** [comment]
BTW, my commit c19a65b is a refactoring. It doesn't change any behavior.

**Comment by maresb** [comment]
Nevermind, I got it.

**Comment by tedder** [comment]
Thanks!

**Comment by maresb** [comment]
I'm preparing a release...

**Comment by maresb** [comment]
v1.4.1 just came out
