### ISSUE TITLE
Option to change font size

### ISSUE THREAD

**Issue by jckoester** [computerlyrik/dymoprint#7]
It would be great to have an option to change the font size. I need to create labels witrh a limited width, and sometimes I'd prefer using smaller letters.

**Comment by computerlyrik** [comment]
Please try to manipulate FONT_SIZERATIO in dymoprint executable.

If you can tell me which setting does fit to font sizes in px, pt, em or 
else

i will add some configuration to .ini and document it.

Thanks!

Am 24.02.2016 um 18:11 schrieb Jan Köster:

**Comment by computerlyrik** [comment]
Closed due to inactivity
